---
# handlers file for roles/dc_authelia
- name: Restart authelia
  community.docker.docker_container:
    name: "{{ dc_authelia_container_name }}"
    state: started
    restart: true
  when: dc_authelia_restart_container_on_template_change | default(true)
