---
# defaults file for roles/pve_vm
# ? ######################################################################################## #
# *                                  Global Variables used                                   #
# ? ######################################################################################## #

# timezone
# system_locale
# ssh_port
# primary_user_name
# primary_user_hashed_pw
# primary_user_pub_key
# pve_storage
# vms_net_gateway
# vms_net_dns_server

# ? ######################################################################################## #
# *                                  Docker Container Variables                              #
# ? ######################################################################################## #

pve_vm_start_after_create: true
pve_vm_prune: false # ! This will completely remove the VM! Mostly for testing purposes
