---
# defaults file for roles/pve_vm
# ? ######################################################################################## #
# *                                  Global Variables used                                   #
# ? ######################################################################################## #

# timezone
# system_locale
# ssh_port
# primary_user_name
# primary_user_hashed_pw
# primary_user_pub_key
# pve_storage
# dc_vms_net_gateway
# dc_vms_net_dns_server

# ? ######################################################################################## #
# *                                  Docker Container Variables                              #
# ? ######################################################################################## #

pve_vm_start_after_create: true
pve_vm_prune: false # ! This will completely remove the VM! Mostly for testing purposes
pve_vm_enable_uefi: true  # Set to true if you want UEFI enabled by default
# pve_vm_automation_files_dir: /opt/pve_automation
pve_vm_base_image_to_use: ubuntu_2404

# Ubuntu 2404 template
pve_vm_role_template_to_use: ubuntu_2404_homelab # Has to match the folder name inside templates of this role
pve_vm_image_url: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
pve_vm_image_destination: "/var/lib/vz/template/iso"
pve_vm_id: 92404  # Default template ID, adjust as needed
pve_vm_name: "ubuntu-2404-template"
pve_vm_memory: 2048
# pve_vm_balloon: 1024  # uncomment if you want a balloon
pve_vm_sockets: 1
pve_vm_cores: 2
# pve_vm_j2templates_dir: "{{ pve_vm_automation_files_dir }}/templates"
pve_vm_hostname: "ubuntu-2404-template"
pve_vm_fqdn: "{{ pve_vm_hostname }}.{{ domain_1 | default(dc_vms_net_internal_domain_name) }}"
pve_vm_disk_size: "16G"
# pve_vm_mac_address_0: ""
pve_vm_net_prefix_length_0: "{{ dc_vms_net_prefix_length }}"
pve_vm_ipv4_address_0: "{{ dc_vms_net_vm_default_ip }}"
pve_vm_bridge_0_name: "{{ dc_vms_net_bridge_name }}"
