---
# defaults file for roles/pve_vm
# TODO: Variables which has to be passed through the playbook or on import of this task file
# ! Mandatory variables
  # vars:
  #   vm_primary_user_pub_key: => "ssh-rsa AAAAB..."  # Your public SSH key

pve_vm_prune: false # This will completely remove the VM! Mostly for testing purposes
pve_vm_primary_user_name: "{{ primary_user_name | default('wasd') }}"
pve_vm_primary_user_hashed_pw: "{{ primary_user_hashed_pw | default('$6$LCOTQrP6OD6fFxR5$okd0.2iW9bRxICAmFRM47o9nKJh7f9GdrGXNj/WTNR9QyssYrpsV07cBFxkIxg83.X9M0xyqL31c9st4BShW61') }}" # 404PasswordNotFound
pve_vm_primary_user_uid: "{{ primary_user_uid | default(1022) }}"
pve_vm_primary_user_gid: "{{ primary_user_gid | default(1022) }}"
pve_vm_storage: "{{ pve_storage | default('local-zfs') }}"
pve_vm_enable_uefi: true  # Set to true if you want UEFI enabled by default
# pve_vm_automation_files_dir: /opt/pve_automation
pve_vm_base_image_to_use: ubuntu_2404
pve_vm_timezone: "{{ timezone | default('America/New_York') }}"
pve_vm_locale: "{{ system_locale | default('en_US.UTF-8') }}"
pve_vm_primary_user_pub_key: "{{ primary_user_pub_key }}"

# Ubuntu 2404 template
pve_vm_role_template_to_use: ubuntu_2404_homelab # Has to match the folder name inside templates of this role
pve_vm_image_url: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
pve_vm_image_destination: "/var/lib/vz/template/iso"
pve_vm_id: 92404  # Default template ID, adjust as needed
pve_vm_name: "ubuntu-2404-template"
pve_vm_memory: 2048
# pve_vm_balloon: 1024  # uncomment if you want a balloon
pve_vm_sockets: 1
pve_vm_cores: 2
# pve_vm_j2templates_dir: "{{ pve_vm_automation_files_dir }}/templates"
pve_vm_hostname: "ubuntu-2404-template"
pve_vm_fqdn: "{{ pve_vm_hostname }}.{{ domain_1 | default(dc_demo_net_domain_name) }}"
pve_vm_ssh_port: "{{ ssh_port | default(2222) }}"
pve_vm_disk_size: "16G"
pve_vm_gateway_ip: "{{ dc_demo_net_gateway }}"
pve_vm_domain_name: "{{ domain_1 | default({{dc_demo_net_domain_name}}) }}"
pve_vm_dns_server: "{{ dc_demo_net_dns_server }}"
# pve_vm_mac_address_0: ""
pve_vm_net_prefix_length_0: "{{ dc_demo_net_prefix_length }}"
pve_vm_ipv4_address_0: "{{ dc_demo_net_vm_default_ip }}"
pve_vm_bridge_0_name: "{{ vm_default_bridge | default('vmbr90') }}"
