---
# handlers file for roles/pve_vm
- name: Set file permissions
  ansible.builtin.file:
    path: "{{ pve_vm_obj.image_destination }}/{{ pve_vm_obj.image_url | basename }}"
    mode: '0644'
  when: download_result.changed

- name: Update GRUB
  ansible.builtin.command: update-grub
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  changed_when: true

- name: Update Initramfs
  ansible.builtin.command: update-initramfs -u
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  changed_when: true
