---
# tasks file for roles/dc_nginx
# ! Actually just for testing. Not prod rdy !
- name: Install docker compose authentik with inline definition
  community.docker.docker_compose_v2:
    project_name: "nginx"  # eg: authentik
    definition:
      # ! --------------------------- Networks --------------------------- ! #
      networks:
        traefik_net:
          name: "{{ dc_traefik_net_name }}"  # eg: traefik_net
          external: true  # indicating that it's a pre-existing network not managed by this Docker Compose file.


      # * ---------------------------- App ------------------------------ * #
      services:
        nginx:
          image: nginx:latest
          container_name: "nginx"
          networks:
            traefik_net:
          labels:
            traefik.enable: "true"
            traefik.http.routers.nginx.entrypoints: "websecure"
            traefik.http.routers.nginx.rule: "Host(`nginx.{{ domain_1 }}`)"
            traefik.http.routers.nginx.service: "nginx-svc"
            traefik.http.services.nginx-svc.loadbalancer.server.port: "80"
            # traefik.http.routers.nginx.middlewares: "middlewares-authentik@file"
            traefik.http.routers.nginx.middlewares: "chain-no-auth@file"
          restart: unless-stopped
