---
# handlers file for roles/dc_promtail
- name: Restart container
  community.docker.docker_container:
    name: "{{ app_name }}-promtail"
    state: started
    restart: true
  when: dc_promtail_restart_container_on_template_change | default(true)
