---
# defaults file for roles/dc_crowdsec
# * ----------------- Container Configuration -------------------- * #
## * Container variables
dc_crowdsec_container_name: "crowdsec"
# dc_crowdsec_create_with_userns: false # ! To many problems... odd container therefore host mode
dc_crowdsec_image_version: "latest"
# dc_crowdsec_u_g_id: 22005 # ! to many problems... odd container therefore host mode
dc_crowdsec_port: 8080

## * Network settings
# dc_crowdsec_net_base: 10.100.0
# dc_crowdsec_net_address: "{{ dc_crowdsec_net_base }}.0"
# dc_crowdsec_net_prefix_length: 29 # 6 usable octets eg 10.100.0.2 - 10.100.0.6
# dc_crowdsec_net_cidr: "{{ dc_crowdsec_net_address }}/{{ dc_crowdsec_net_prefix_length }}"  # 10.100.0.0/29

# dc_crowdsec_net_app_ip: "{{ dc_crowdsec_net_base }}.2"  # 10.100.0.2/29
# dc_crowdsec_net_db_ip: "{{ dc_crowdsec_net_base }}.3"  # 10.100.0.3/29
# dc_crowdsec_net_redis_ip: "{{ dc_crowdsec_net_base }}.4"  # 10.100.0.4/29


# * ---------------- crowdsec-bouncer Configuration ------------------- * #
## Environment variables
dc_crowdsec_bouncer_create_with_userns: true
dc_crowdsec_bouncer_image_version: "latest"
dc_crowdsec_bouncer_u_g_id: 22006 # with userns --> 122006
# dc_crowdsec_db_superuser_pw: ""  # Empty for generated password ; superuser name --> postgres
# dc_crowdsec_db_name: "authelia"
# dc_crowdsec_db_user_name: "authelia"
# dc_crowdsec_db_user_pw: ""  # Empty for generated password
# dc_crowdsec_db_port: 5432
