# yamllint disable rule:colons
# ? ######################################################################################## #
# !                                         Networks                                         #
# ? ######################################################################################## #

# ? -----------------------------------------------------------------------------
# *                       untagged Default (mostly VLAN 1)                      *
# ? -----------------------------------------------------------------------------
# ? override it through z_network.yml if needed to match your network
default_net:
  vlan_id:      1
  bridge_name:  "vmbr0"
  subnet:       "192.168.1.0/24"
  gateway:      "192.168.1.1"
  dns_server:   "192.168.1.1"
  search_domain: "default.{{ domain_1 }}"

# ? Since not everyone has multiuple pve servers for each env, we can use the same server for each env. Recommended to also asign an ip into the prod mgmt network.
default_net_pve_aio_ip: "{{ default_net_base }}.210" # "192.168.1.210"


# ? -----------------------------------------------------------------------------
# *                                VLANs and co                                 *
# ? -----------------------------------------------------------------------------

mgmt_net:
  prod:
    vlan_id:      1005
    bridge_name:  "vmbr1005"
    subnet:       "10.10.5.0/24"
    gateway:      "10.10.5.3"
    dns_server:   "10.10.5.3"
    search_domain: "mgmt.{{ domain_1 }}"
  placeh1:
    vlan_id:      1105
    bridge_name:  "vmbr1105"
    subnet:       "10.11.5.0/24"
    gateway:      "10.11.5.3"
    dns_server:   "10.11.5.3"
    search_domain: "placeh1-mgmt.{{ domain_1 }}"
  beta:
    vlan_id:      1205
    bridge_name:  "vmbr1205"
    subnet:       "10.12.5.0/24"
    gateway:      "10.12.5.3"
    dns_server:   "10.12.5.3"
    search_domain: "beta-mgmt.{{ domain_1 }}"
  placeh2:
    vlan_id:      1305
    bridge_name:  "vmbr1305"
    subnet:       "10.13.5.0/24"
    gateway:      "10.13.5.3"
    dns_server:   "10.13.5.3"
    search_domain: "placeh2-mgmt.{{ domain_1 }}"
  dev:
    vlan_id:      1405
    bridge_name:  "vmbr1405"
    subnet:       "10.14.5.0/24"
    gateway:      "10.14.5.3"
    dns_server:   "10.14.5.3"
    search_domain: "dev-mgmt.{{ domain_1 }}"
  placeh3:
    vlan_id:      1505
    bridge_name:  "vmbr1505"
    subnet:       "10.15.5.0/24"
    gateway:      "10.15.5.3"
    dns_server:   "10.15.5.3"
    search_domain: "placeh3-mgmt.{{ domain_1 }}"
  demo:
    vlan_id:      1605
    bridge_name:  "vmbr1605"
    subnet:       "10.16.5.0/24"
    gateway:      "10.16.5.3"
    dns_server:   "10.16.5.3"
    search_domain: "demo-mgmt.{{ domain_1 }}"
  placeh4:
    vlan_id:      1705
    bridge_name:  "vmbr1705"
    subnet:       "10.17.5.0/24"
    gateway:      "10.17.5.3"
    dns_server:   "10.17.5.3"
    search_domain: "placeh4-mgmt.{{ domain_1 }}"

vms_net:
  prod:
    vlan_id:      1090
    bridge_name:  "vmbr1090"
    subnet:       "10.10.90.0/24"
    gateway:      "10.10.90.3"
    dns_server:   "10.10.90.3"
    search_domain: "vms.{{ domain_1 }}"
  placeh1:
    vlan_id:      1190
    bridge_name:  "vmbr1190"
    subnet:       "10.11.90.0/24"
    gateway:      "10.11.90.3"
    dns_server:   "10.11.90.3"
    search_domain: "placeh1-vms.{{ domain_1 }}"
  beta:
    vlan_id:      1290
    bridge_name:  "vmbr1290"
    subnet:       "10.12.90.0/24"
    gateway:      "10.12.90.3"
    dns_server:   "10.12.90.3"
    search_domain: "beta-vms.{{ domain_1 }}"
  placeh2:
    vlan_id:      1390
    bridge_name:  "vmbr1390"
    subnet:       "10.13.90.0/24"
    gateway:      "10.13.90.3"
    dns_server:   "10.13.90.3"
    search_domain: "placeh2-vms.{{ domain_1 }}"
  dev:
    vlan_id:      1490
    bridge_name:  "vmbr1490"
    subnet:       "10.14.90.0/24"
    gateway:      "10.14.90.3"
    dns_server:   "10.14.90.3"
    search_domain: "dev-vms.{{ domain_1 }}"
  placeh3:
    vlan_id:      1590
    bridge_name:  "vmbr1590"
    subnet:       "10.15.90.0/24"
    gateway:      "10.15.90.3"
    dns_server:   "10.15.90.3"
    search_domain: "placeh3-vms.{{ domain_1 }}"
  demo:
    vlan_id:      1690
    bridge_name:  "vmbr1690"
    subnet:       "10.16.90.0/24"
    gateway:      "10.16.90.3"
    dns_server:   "10.16.90.3"
    search_domain: "demo-vms.{{ domain_1 }}"
  placeh4:
    vlan_id:      1790
    bridge_name:  "vmbr1790"
    subnet:       "10.17.90.0/24"
    gateway:      "10.17.90.3"
    dns_server:   "10.17.90.3"
    search_domain: "placeh4-vms.{{ domain_1 }}"

pve_base_id:
  prod: 1000
  placeh1: 1100
  beta: 1200
  placeh2: 1300
  dev: 1400
  placeh3: 1500
  demo: 1600
  placeh4: 1700

# ? All vms will inherit this object. Overrides them here to set the defaults or by vm specific vars
# ? Inherit happens inside the role: pve_vm/tasks/main.yml
ubuntu_2404_vm_base_obj:
  pve_id: 92404 # Default template ID
  template_to_use: ubuntu_2404_homelab # Has to match the folder name inside templates of this role
  image_url: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
  image_destination: "/var/lib/vz/template/iso"
  hostname: "ubuntu-2404-template"
  prefer_fqdn_over_hostname: false
  sockets: 1
  cores: 2
  memory: 2048
  # balloon: 1024  # uncomment if you want a balloon
  disk_size: "16G"
  uefi_enabled: true
  bridge_0_name: "{{ vms_net[env].bridge_name }}" # ! Note: The network is hardcoded in templates/network.yml.j2 since net intended to be changed
  # bridge_0_mac_address: ""

# ? Docker network will use 10.x.0.0/16
# ? x will be 100 + vm_id eg = 109 => 10.109.0.0/16 which will be splitted also into 8 subnets for each cidr
# ? Therefore it is planned to use the ranges of 10.100.0.0/16 - 10.199.0.0/16 which equals to 100 vms.
# ? Therefore also those vms will all have unique docker subnets
vm09_aio:
  vm_id: 9 # Is used for like the docker subnets. Therefore use only 0-99
  pve_id: "{{ pve_base_id[env] + 9 }}"  # Overrides the base object
  hostname: "{{ env }}-vm09-aio"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('9') | ansible.utils.ipaddr('address') }}" # 10.10.90.9 (prod) / 10.11.90.9 (placeh1) / 10.12.90.9 (beta) / ...

vm10_ingress:
  vm_id: 10
  pve_id: "{{ pve_base_id[env] + 10 }}"
  hostname: "{{ env }}-vm10-ingress"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('10') | ansible.utils.ipaddr('address') }}" # 10.10.90.10 (prod) / 10.11.90.10 (placeh1) / 10.12.90.10 (beta) / ...

vm20_metrics:
  vm_id: 20
  pve_id: "{{ pve_base_id[env] + 20 }}"
  hostname: "{{ env }}-vm20-metrics"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('20') | ansible.utils.ipaddr('address') }}" # 10.10.90.20 (prod) / 10.11.90.20 (placeh1) / 10.12.90.20 (beta) / ...

vm31_application_1:
  vm_id: 31
  pve_id: "{{ pve_base_id[env] + 31 }}"
  hostname: "{{ env }}-vm31-application-1"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('31') | ansible.utils.ipaddr('address') }}" # 10.10.90.31 (prod) / 10.11.90.31 (placeh1) / 10.12.90.31 (beta) / ...

vm32_application_2:
  vm_id: 32
  pve_id: "{{ pve_base_id[env] + 32 }}"
  hostname: "{{ env }}-vm32-application-2"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('32') | ansible.utils.ipaddr('address') }}" # 10.10.90.32 (prod) / 10.11.90.32 (placeh1) / 10.12.90.32 (beta) / ...

vm41_multimedia_1:
  vm_id: 41
  pve_id: "{{ pve_base_id[env] + 41 }}"
  hostname: "{{ env }}-vm41-multimedia-1"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('41') | ansible.utils.ipaddr('address') }}" # 10.10.90.41 (prod) / 10.11.90.41 (placeh1) / 10.12.90.41 (beta) / ...

vm42_multimedia_2:
  vm_id: 42
  pve_id: "{{ pve_base_id[env] + 42 }}"
  hostname: "{{ env }}-vm42-multimedia-2"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('42') | ansible.utils.ipaddr('address') }}" # 10.10.90.42 (prod) / 10.11.90.42 (placeh1) / 10.12.90.42 (beta) / ...

vm99_testing:
  vm_id: 99
  pve_id: "{{ pve_base_id[env] + 99 }}"
  hostname: "{{ env }}-vm99-testing"
  ip: "{{ vms_net[env].subnet | ansible.utils.ipaddr('99') | ansible.utils.ipaddr('address') }}" # 10.10.90.99 (prod) / 10.11.90.99 (placeh1) / 10.12.90.99 (beta) / ...


# ! --------------------------- Notes --------------------------- ! #
# ? The VMs are by default only in the vms network. The MGMT is more intended for real servers like pve to put on. However
# ? in case you want to put your vms also in the mgmt network, here is a overview on which IPs you shouldnt use for other purposes in your network if you want consistency
# Environment,VM ID,Type,Name,Proxmox ID,VLAN mgmt,VLAN vms,VLAN mgmt IP,VLAN vms IP
# prod,10,ingress,prod-vm10-ingress,1010,1005,1090,10.10.5.10/24,10.10.90.10/24
# prod,20,metrics,prod-vm20-metrics,1020,1005,1090,10.10.5.20/24,10.10.90.20/24
# prod,31,application1,prod-vm31-application1,1031,1005,1090,10.10.5.31/24,10.10.90.31/24
# placeh1,10,ingress,placeh1-vm10-ingress,1110,1105,1190,10.11.5.10/24,10.11.90.10/24
# placeh1,20,metrics,placeh1-vm20-metrics,1120,1105,1190,10.11.5.20/24,10.11.90.20/24
# placeh1,31,application1,placeh1-vm31-application1,1131,1105,1190,10.11.5.31/24,10.11.90.31/24
# beta,10,ingress,beta-vm10-ingress,1210,1205,1290,10.12.5.10/24,10.12.90.10/24
# beta,20,metrics,beta-vm20-metrics,1220,1205,1290,10.12.5.20/24,10.12.90.20/24
# beta,31,application1,beta-vm31-application1,1231,1205,1290,10.12.5.31/24,10.12.90.31/24
# placeh2,10,ingress,placeh2-vm10-ingress,1310,1305,1390,10.13.5.10/24,10.13.90.10/24
# placeh2,20,metrics,placeh2-vm20-metrics,1320,1305,1390,10.13.5.20/24,10.13.90.20/24
# placeh2,31,application1,placeh2-vm31-application1,1331,1305,1390,10.13.5.31/24,10.13.90.31/24
# dev,10,ingress,dev-vm10-ingress,1410,1405,1490,10.14.5.10/24,10.14.90.10/24
# dev,20,metrics,dev-vm20-metrics,1420,1405,1490,10.14.5.20/24,10.14.90.20/24
# dev,31,application1,dev-vm31-application1,1431,1405,1490,10.14.5.31/24,10.14.90.31/24
# placeh3,10,ingress,placeh3-vm10-ingress,1510,1505,1590,10.15.5.10/24,10.15.90.10/24
# placeh3,20,metrics,placeh3-vm20-metrics,1520,1505,1590,10.15.5.20/24,10.15.90.20/24
# placeh3,31,application1,placeh3-vm31-application1,1531,1505,1590,10.15.5.31/24,10.15.90.31/24
# demo,10,ingress,demo-vm10-ingress,1610,1605,1690,10.16.5.10/24,10.16.90.10/24
# demo,20,metrics,demo-vm20-metrics,1620,1605,1690,10.16.5.20/24,10.16.90.20/24
# demo,31,application1,demo-vm31-application1,1631,1605,1690,10.16.5.31/24,10.16.90.31/24
# placeh4,10,ingress,placeh4-vm10-ingress,1710,1705,1790,10.17.5.10/24,10.17.90.10/24
# placeh4,20,metrics,placeh4-vm20-metrics,1720,1705,1790,10.17.5.20/24,10.17.90.20/24
# placeh4,31,application1,placeh4-vm31-application1,1731,1705,1790,10.17.5.31/24,10.17.90.31/24
