---
# handlers file for roles/dc_grafana
- name: Restart container
  community.docker.docker_container:
    name: "{{ dc_grafana_container_name }}"
    state: started
    restart: true
  when: dc_grafana_restart_container_on_template_change | default(true)
