---
- name: Create Docker directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: "{{ docker_home }}", mode: '0750', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
    - { path: "{{ docker_appdata }}", mode: '0750', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
    - { path: "{{ docker_custom }}", mode: '0750', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
    - { path: "{{ docker_logs }}", mode: '0750', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
    - { path: "{{ docker_scripts }}", mode: '0750', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
    - { path: "{{ docker_secrets }}", mode: '0700', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
    # - { path: "{{ docker_compose }}", mode: '0750', owner: "{{ docker_provisioning_dockerino_user_name }}", group: "{{ docker_provisioning_dockerino_user_name }}" }
  # loop_control:
  #   label: "{{ item.path }}"
