---
# handlers file for roles/dc_prometheus
- name: Restart container
  community.docker.docker_container:
    name: "{{ app_name }}-prometheus"
    state: started
    restart: true
  when: dc_promtail_restart_container_on_template_change | default(true)
