---
# handlers file for roles/dc_prometheus
- name: Restart prometheus
  community.docker.docker_container:
    name: "{{ app_name if not dc_prometheus_standalone else 'standalone' }}-prometheus"
    state: started
    restart: true
  when: dc_prometheus_restart_container_on_template_change | default(true)
