---
# handlers file for roles/traefik
- name: Restart traefik
  community.docker.docker_container:
    name: "{{ dc_traefik_container_name }}"
    state: started
    restart: true
  when: dc_traefik_restart_container_on_template_change | default(true)
