---
# tasks file for roles/dc_vector
# TODO: Variables which has to be passed through the playbook or on import of this task file
# ! Mandatory variables
  # vars:
  #   dc_vector_parent_app_name: => traefik, portainer, grafana, netbox
# ? Optional variables

- name: Create Vector & Socket Proxy
  block:
  # ? Does not work correctly with the socketproxy.

  # * --------------------------- App --------------------------- *
    - name: Create vector for --> {{ dc_vector_parent_app_name }}
      vars:
        container_type: "vector" # => app, db, redis, loki, vector
        user: "{{ (dc_vector_create_with_userns | bool) | ternary(dc_vector_u_g_id + 100000, dc_vector_u_g_id) }}"
        group: "{{ (dc_vector_create_with_userns | bool) | ternary(dc_vector_u_g_id + 100000, dc_vector_u_g_id) }}"
      block:
        - name: '[Required] filesystem_manager role'
          ansible.builtin.import_role:
            name: filesystem_manager
          vars:
            filesystem_manager_app_name: "{{ dc_vector_parent_app_name }}"
            filesystem_manager_restart_container_on_template_change: true
            filesystem_manager_appdata_directories_to_create:
              - path: "config"
            filesystem_manager_appdata_templates_in_directory_to_copy:
              - src: "{{ playbook_dir | dirname }}/roles/dc_vector/templates/shared"
                dest: "config"
              - src: "{{ playbook_dir | dirname }}/roles/dc_vector/templates/{{ dc_traefik_type }}"
                dest: "config"
            # filesystem_manager_appdata_templates_to_copy:
            #   - src: "shared/common.yml.j2"
            #     dest: "config/common.yml"
            #   - src: "shared/system_metrics.yml.j2"
            #     dest: "config/system_metrics.yml"
            #   - src: "shared/system_logs.yml.j2"
            #     dest: "config/system_logs.yml"
            #   - src: "shared/docker_logs.yml.j2"
            #     dest: "config/docker_logs.yml"
            #   - src: "ingress/sinks.yml.j2"
            #     dest: "config/sinks.yml"
              # - src: "vector.yml.j2"
              #   dest: "config/vector.yml"

        - name: Install docker compose vector with inline definition
          vars:
            docker_networks: >-
              {{
                {
                  "traefik_net": {
                    "name": dc_traefik_net.name,
                    "external": true
                  },
                }
                | combine(
                  {
                    "app_net": {
                      "name": dc_vector_parent_app_name ~ "_net",
                      "external": true
                    }
                  } if not dc_vector_standalone else {}
                )
              }}

            container_networks: >-
              {{
                {
                  "traefik_net": {
                    "ipv4_address": dc_traefik_net.vector_ip
                  }
                }
                | combine(
                  {
                    "app_net": {
                      "ipv4_address": dc_vector_net_ip
                    }
                  } if not dc_vector_standalone else {}
                )
              }}

          community.docker.docker_compose_v2:
            project_name: "{{ dc_vector_parent_app_name }}-vector" # eg: grafana-vector
            definition:
              # ! --------------------------- Networks --------------------------- ! #
              networks: "{{ docker_networks }}"


              # * ---------------------------- App ------------------------------ * #
              services:
                vector:
                  image: "{{ dc_vector_image }}"
                  container_name: "{{ dc_vector_parent_app_name }}-vector"  # eg: grafana-vector
                  restart: unless-stopped
                  security_opt:
                    - no-new-privileges:true
                  privileged: false
                  # userns_mode: "{{ 'host' if dc_vector_create_with_userns | bool == false else 'remap' }}"
                  # user: "{{ dc_vector_u_g_id }}:{{ dc_vector_u_g_id }}"
                  userns_mode: "host" # Until im sure everything works
                  # user: "0:0" # Until im sure everything works
                  deploy:
                    resources:
                      limits:
                        cpus: '0.50'
                  command: ["-c", "/etc/vector/*.yml"]
                  extra_hosts:
                    # - "traefik-ingress.{{ domain_1 }}:{{ dc_traefik_net_ip }}"  # Yes, this is correct!
                    # - "traefik-metrics.{{ domain_1 }}:{{ dc_traefik_net_ip }}"  # Yes, this is correct!
                    - "loki-metrics.{{ domain_1 }}:{{ vm20_metrics.ip if (dc_vector_standalone | default(false) | bool) else dc_vector_net_ip }}"
                  networks: "{{ container_networks }}"
                  # ports:
                  #   - "{{ dc_vector_port }}:8686"
                  #   - 9598:9598 # Prometheus Exporter default port
                  volumes:
                    - "{{ appdata_type_path }}/config:/etc/vector"
                    # - "{{ appdata_type_path }}/config/common.yml:/etc/vector/common.yml:ro"
                    # - "{{ appdata_type_path }}/config/system_metrics.yml:/etc/vector/system_metrics.yml:ro"
                    # - "{{ appdata_type_path }}/config/system_logs.yml:/etc/vector/system_logs.yml:ro"
                    # - "{{ appdata_type_path }}/config/docker_logs.yml:/etc/vector/docker_logs.yml:ro"
                    # - "{{ appdata_type_path }}/config/sinks.yml:/etc/vector/sinks.yml:ro"
                    # # # - "{{ appdata_type_path }}/config/vector.yml:/etc/vector/vector.yml:ro"
                    # - /sys/fs/cgroup:/sys/fs/cgroup:ro
                    # - /proc:/rootfs/proc:ro
                    # - /sys:/rootfs/sys:ro
                    # - /var/log:/var/log:ro
                    - /opt/docker/logs:/opt/docker/logs:ro
                    - /var/run/docker.sock:/var/run/docker.sock:ro
                  environment:
                    # DOCKER_HOST: "{{ dc_vector_socketproxy_net_ip }}:2375"
                    VECTOR_LOG: "{{ dc_grafana_vector_log_level }}"  # trace, debug, info, warn, error, off default: info
                    # HOST_PROC: /rootfs/proc
                    # HOST_SYS: /rootfs/sys
                    # HOST_ETC: /rootfs/etc
                  labels:
                    traefik.enable: "true"
                    # ? This will need api to be enabled on the common.yml file
                    # * HTTP Router for Vector (default port 8686)
                    traefik.http.routers.vector-rtr.entrypoints: "websecure"
                    traefik.http.routers.vector-rtr.rule: "Host(`vector-{{ dc_traefik_type }}.{{ domain_1 }}`)"
                    traefik.http.routers.vector-rtr.middlewares: "chain-authelia@file"
                    traefik.http.routers.vector-rtr.service: "vector-svc"
                    # * HTTP Service for Vector (default port 8686)
                    traefik.http.services.vector-svc.loadbalancer.server.port: "{{ dc_vector_port }}" # default: "8686"


                    # * HTTP Router Without Authentication for Vector Prometheus Metrics (port 9598)
                    traefik.http.routers.vector-metrics-rtr-noauth.entrypoints: "websecure"
                    traefik.http.routers.vector-metrics-rtr-noauth.rule: "Host(`vector-{{ dc_traefik_type }}.{{ domain_1 }}`) && Path(`/metrics`) && ClientIP(`{{ vm20_metrics.ip }}/32`)"
                    traefik.http.routers.vector-metrics-rtr-noauth.middlewares: "chain-no-auth@file"
                    traefik.http.routers.vector-metrics-rtr-noauth.service: "vector-metrics-svc"

                    # * HTTP Router With Authentication for Vector Prometheus Metrics (port 9598)
                    traefik.http.routers.vector-metrics-rtr.entrypoints: "websecure"
                    traefik.http.routers.vector-metrics-rtr.rule: "Host(`vector-{{ dc_traefik_type }}.{{ domain_1 }}`)"
                    traefik.http.routers.vector-metrics-rtr.middlewares: "chain-authelia@file"
                    traefik.http.routers.vector-metrics-rtr.service: "vector-metrics-svc"

                    # * HTTP Service for Vector Prometheus Metrics (port 9598)
                    traefik.http.services.vector-metrics-svc.loadbalancer.server.port: "{{ dc_vector_prometheus_exporter_port }}" # default: "9598"


# ! --------------------------- Notes --------------------------- ! #
# Depending on the logs wanted, it is best to use this container as root. Since this will not be exposed, this should be acceptable.
# Seams not to work correctly with the socketproxy.
# ? It is recommended to use the namespace: node to make it compatible with other dashboards made for like the node exporter and additional an extra label like parser: vector or node-exporter

# Vector is more than enough for system metrics compared to node exporter. Therefore I decided to use vector and not node exporter.

# Recommended to use all logs (systems, containers, services, etc.) to at least info level
# https://vector.dev/docs/reference/api/
# http://10.0.90.20:8686/playground to test
# https://playground.vrl.dev/
# https://vector.dev/docs/reference/vrl/examples/

# When using the api request, the source is the important part which will be shown in Grafana. Not the _index, _id or _score.

# Promtail works at a message level, Vector includes also the metadata and then the message as a own field.
# Vector also seams to include by default all metadata fields while promtail needs to be exctracted like the container name from __meta_docker_container_name
# The Logs in Grafana always works at the message level. Therefore this is what gets splitted as a single log entry.
# Therefore if I want good Logs, I have to manipulate the message field, or declare a own one and set this in grafana to be used when using Elasticsearch as datasource.
# The message part has still to be parsed to get the collors based on log level (error, info, warn, ...)
# ? also a important message. Labels are meant to be the fields in grafana. Not to be confused with docker labels.
