---
# handlers file for roles/dc_alloy
- name: Restart alloy
  community.docker.docker_container:
    name: "{{ dc_grafana_container_name if not dc_alloy_standalone else 'standalone' }}-alloy"
    state: started
    restart: true
  when: dc_alloy_restart_container_on_template_change | default(true)
