---
# # system_language: "en_US.UTF-8"
# # keyboard_layout: "us"
# # alpha2code: "us"

# ssh_key_type: "ecdsa-sk"  # comment out for ed25519
# primary_user_pub_key: # Add your public key content here

ansible_ssh_private_key_file: "{{ '~/.ssh/id_ecdsa_sk' if ssh_key_type is defined and ssh_key_type == 'ecdsa-sk' else '~/.ssh/id_ed25519' }}"
ansible_port: "{{ ssh_port | default(2222) }}"
ansible_ssh_common_args: '-o IdentitiesOnly=yes'


# Container IDs


################################################################################################################################

# Template
# * ----------------- Container Configuration -------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * --------------------- DB Configuration ------------------------ * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * ------------------- Redis Configuration ---------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * ------------------- SocketProxy Configuration ---------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings
