---
# ? ######################################################################################## #
# !                            User specified mandatory variables                            #
# ? ######################################################################################## #
# * Uncomment and set it accordingly

# primary_user_pub_key: # Add your public key content here


# ? ######################################################################################## #
# *                                     Common Variables                                     #
# ? ######################################################################################## #

timezone: "America/New_York"
system_locale: "en_US.UTF-8"
system_language: "en_US.UTF-8"
keyboard_layout: "us"
alpha2code: "us"
domain_1: 'demo.net'

# ssh_key_type: "ecdsa-sk"  # comment out for ed25519
ssh_port: 2222

demo_auth_user: "AOAUserNotFound" # Eg: Logins for => authelia, traefik etc.
demo_auth_user_email: "{{ demo_auth_user }}@{{ domain_1 }}" # eg: AOAUserNotFound@demo.net
demo_auth_user_pw: "404PasswordNotFound"
demo_auth_user_pw_htpasswd: "$apr1$z19bu7pc$F4eZc.lSBtThI29L366PS1" # "404PasswordNotFound" "404PasswordNotFound" # https://www.web2generators.com/apache-tools/htpasswd-generator
demo_auth_pw_hashed: '$6$LCOTQrP6OD6fFxR5$okd0.2iW9bRxICAmFRM47o9nKJh7f9GdrGXNj/WTNR9QyssYrpsV07cBFxkIxg83.X9M0xyqL31c9st4BShW61' # 404PasswordNotFound # openssl passwd -6 ; Used for linux user hashed pw
demo_auth_pw_argon2id: "$argon2id$v=19$m=65536,t=3,p=4$lt66bWx+X/afiGpaSi1gug$XpFusSEhnv7/j83M8d8RoQmXM/L+uZxpSrMx4eJZkD8" # 404PasswordNotFound
demo_auth_pw_bcrypt: "$2a$10$i2MGNwuNW9iq1R5HJz9SCOt/nPQuf/jvEo5wq5dR7MHnpMlWx9EGa" # 404PasswordNotFound

ansible_ssh_private_key_file: "{{ '~/.ssh/id_ecdsa_sk' if ssh_key_type is defined and ssh_key_type == 'ecdsa-sk' else '~/.ssh/id_ed25519' }}"
ansible_port: "{{ ssh_port | default(2222) }}"
ansible_ssh_common_args: '-o IdentitiesOnly=yes'

docker_home: "/opt/docker"
# Subdirectories for specific types of Docker-related files
docker_appdata: "{{ docker_home }}/appdata"  # Application data
docker_custom: "{{ docker_home }}/custom"    # Custom configurations
docker_logs: "{{ docker_home }}/logs"        # Log files
docker_scripts: "{{ docker_home }}/scripts"  # Utility scripts
docker_secrets: "{{ docker_home }}/secrets"  # Sensitive data
docker_compose: "{{ docker_home }}/compose"  # compose datafiles


# ? ######################################################################################## #
# !                              Mandatory Container Variables                               #
# ? ######################################################################################## #
# This are crucial variables for an operating container and has to be set

# * >>>>>>>>>>>>>>>>>>> Traefik <<<<<<<<<<<<<<<<<<<
dc_traefik_cf_dns_api_token: ""


# ? ######################################################################################## #
# *                                  Docker Container Variables                              #
# ? ######################################################################################## #

# ? -----------------------------------------------------------------------------
# *                                Container IDs                                *
# ? -----------------------------------------------------------------------------

dc_traefik_u_g_id: 22003 # with userns --> 122003
dc_adguard_u_g_id: 22007 # with userns --> 122007

# ? -----------------------------------------------------------------------------
# *                                  dc_adguard                                 *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                                 dc_authelia                                 *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                                 dc_authentik                                *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                                 dc_crowdsec                                 *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                                 dc_it-tools                                 *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                            dc_postgresql_bitnami                            *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                              dc_redis_bitnami                               *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                             dc_secrets_manager                              *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                               dc_socketproxy                                *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                                  dc_traefik                                 *
# ? -----------------------------------------------------------------------------

# ! ------------------>>> Dependencies <<<------------------ ! #
# ? Has to be set by vars
# timezone
# domain_1
# dc_traefik_cf_dns_api_token

# * ----------->>> Container Configuration <<<--------------- * #
# * >>> Container variables
dc_traefik_container_name: "traefik"
dc_traefik_create_with_userns: true
dc_traefik_image_version: "3.1"
dc_traefik_log_level: "INFO"

dc_traefik_acme_staging_mode: true  # true = LetsEncrypt Staging Server - false = LetsEncrypt Production Server
dc_traefik_crowdsec_enabled: true
dc_traefik_crowdsec_bouncer_key: "" # Empty for generated key

dc_traefik_basic_auth_user: "{{ demo_auth_user }}"
dc_traefik_basic_auth_password_hashed: "{{ demo_auth_user_pw_htpasswd }}" # "404PasswordNotFound" # https://www.web2generators.com/apache-tools/htpasswd-generator
dc_traefik_cloudflare_ip_ranges: >
  173.245.48.0/20, 103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, 141.101.64.0/18,
  108.162.192.0/18, 190.93.240.0/20, 188.114.96.0/20, 197.234.240.0/22, 198.41.128.0/17,
  162.158.0.0/15, 104.16.0.0/13, 104.24.0.0/14, 172.64.0.0/13, 131.0.72.0/22
dc_traefik_local_ip_ranges: ""

# * --------->>> SocketProxy Configuration <<<------------- * #
# * >>> Container variables

## ? Environment variables for socketproxy
dc_traefik_socketproxy_env_log_level: "info"  # debug, info, notice, warning, err, crit, alert and emerg

# * Not always needed - Can expose some information that your service does not need
dc_traefik_socketproxy_env_containers: "1"


# ? -----------------------------------------------------------------------------
# *                                dc_whoami                                    *
# ? -----------------------------------------------------------------------------

# ? -----------------------------------------------------------------------------
# *                               dn_traefik_net                                *
# ? -----------------------------------------------------------------------------


####################################################################################################################################################

# Container defaults/main.yml Template
# * ----------------- Container Configuration -------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * --------------------- DB Configuration ------------------------ * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * ------------------- Redis Configuration ---------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * ------------------- SocketProxy Configuration ---------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings
