---
# ? ######################################################################################## #
# !                            User specified mandatory variables                            #
# ? ######################################################################################## #


# ? ######################################################################################## #
# *                                     Global Variables                                     #
# ? ######################################################################################## #
