---
# # system_language: "en_US.UTF-8"
# # keyboard_layout: "us"
# # alpha2code: "us"

# ssh_key_type: "ecdsa-sk"  # comment out for ed25519
# primary_user_pub_key: # Add your public key content here
# cf_dns_api_token

demo_auth_user: "AOAUserNotFound" # Eg: Logins for => authelia, traefik etc.
# 404PasswordNotFound  # openssl passwd -6 ; Used for linux user hashed pw
demo_auth_pw_hashed: '$6$LCOTQrP6OD6fFxR5$okd0.2iW9bRxICAmFRM47o9nKJh7f9GdrGXNj/WTNR9QyssYrpsV07cBFxkIxg83.X9M0xyqL31c9st4BShW61'
demo_auth_pw_argon2id: "" # 404PasswordNotFound

ansible_ssh_private_key_file: "{{ '~/.ssh/id_ecdsa_sk' if ssh_key_type is defined and ssh_key_type == 'ecdsa-sk' else '~/.ssh/id_ed25519' }}"
ansible_port: "{{ ssh_port | default(2222) }}"
ansible_ssh_common_args: '-o IdentitiesOnly=yes'
domain_1: 'demo.net'  # ! Not the same as dc_demo_net_domain_name !

docker_home: "/opt/docker"
# Subdirectories for specific types of Docker-related files
docker_appdata: "{{ docker_home }}/appdata"  # Application data
docker_custom: "{{ docker_home }}/custom"    # Custom configurations
docker_logs: "{{ docker_home }}/logs"        # Log files
docker_scripts: "{{ docker_home }}/scripts"  # Utility scripts
docker_secrets: "{{ docker_home }}/secrets"  # Sensitive data
docker_compose: "{{ docker_home }}/compose"  # compose datafiles

# Container IDs


################################################################################################################################

# Template
# * ----------------- Container Configuration -------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * --------------------- DB Configuration ------------------------ * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * ------------------- Redis Configuration ---------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings


# * ------------------- SocketProxy Configuration ---------------------- * #
## * Container variables

## * Users configuration (like authelia users or such specific groups). Only if needed

## * Network settings
