# ! ######################## VMs ######################## * #
dc_demo_net_domain_name: "demo.net"
dc_demo_net_base: 10.0.90
dc_demo_net_address: "{{ dc_demo_net_base }}.0"
dc_demo_net_prefix_length: 24
dc_demo_net_cidr: "{{ dc_demo_net_address }}/{{ dc_demo_net_prefix_length }}"
dc_demo_net_gateway: "{{ dc_demo_net_base }}.5"
dc_demo_net_dns_server: "{{ dc_demo_net_gateway }}"

dc_demo_net_vm_default_ip: "{{ dc_demo_net_base }}.100" # "10.0.90.100"
dc_demo_net_vm1_ingress_ip: "{{ dc_demo_net_base }}.10" # "10.0.90.10"
dc_demo_net_vm2_metrics_ip: "{{ dc_demo_net_base }}.20" # "10.0.90.20"
dc_demo_net_vm3_application_1_ip: "{{ dc_demo_net_base }}.31" # "10.0.90.31"


# ! ######################## Apps ######################## * #
# * ----------------- Traefik ----------------- ! #


# * ----------------- Authelia ----------------- ! #


# ! ################### Socket Proxyies ################### * #
# * ----------------- Traefik ----------------- ! #
