---
# tasks file for roles/dc_grafana
- name: Create Grafana with Loki and Promtail
  vars:
    app_name: "{{ dc_grafana_container_name }}" # "grafana"
    db_name: "{{ dc_grafana_db_name }}" # "grafana"
    db_user_name: "{{ dc_grafana_db_user_name }}" # "grafana"
    db_user_pw: "{{ dc_grafana_db_user_pw }}"  # ! MUST BE HERE BECAUSE SHARED !
    db_port: "{{ dc_grafana_db_port }}" # "5432"
  block:
  # ! --------------------------- Networks --------------------------- ! #
    - name: Create network for --> {{ app_name }}
      community.docker.docker_network:
        name: "{{ app_name }}_net"
        driver: bridge
        internal: true
        ipam_config:
          - subnet: "{{ dc_grafana_net_cidr }}"


  # * ------------------------ Grafana DB ------------------------ * #
    - name: Include postgresql role
      when: not dc_grafana_use_sqlite
      ansible.builtin.import_role:
        name: dc_postgresql_bitnami
      vars:
        dc_postgresql_bitnami_create_with_userns: "{{ dc_grafana_db_create_with_userns }}"
        dc_postgresql_bitnami_image_version: "{{ dc_grafana_db_image_version }}"
        dc_postgresql_bitnami_db_superuser_pw: "{{ dc_grafana_db_superuser_pw }}"
        dc_postgresql_bitnami_db_name: "{{ dc_grafana_db_name }}"
        dc_postgresql_bitnami_db_user_name: "{{ dc_grafana_db_user_name }}"
        dc_postgresql_bitnami_db_port: "{{ dc_grafana_db_port }}"
        dc_postgresql_bitnami_net_ip: "{{ dc_grafana_net_db_ip }}"


  # * ------------------------ Grafana Loki ------------------------ * #
    - name: Include loki role
      ansible.builtin.import_role:
        name: dc_loki
      vars:
        dc_loki_create_with_userns: "{{ dc_grafana_loki_create_with_userns }}"
        dc_loki_image_version: "{{ dc_grafana_loki_image_version }}"
        dc_loki_net_ip: "{{ dc_grafana_net_loki_ip }}"


  # # * ------------------------ Grafana Promtail ------------------------ * #
  #   - name: Include promtail role
  #     ansible.builtin.import_role:
  #       name: dc_promtail
  #     vars:
  #       dc_promtail_create_with_userns: "{{ dc_grafana_promtail_create_with_userns }}"
  #       dc_promtail_image_version: "{{ dc_grafana_promtail_image_version }}"
  #       dc_promtail_net_ip: "{{ dc_grafana_net_promtail_ip }}"


  # # * ------------------------ Grafana Node Exporter ------------------------ * #
  #   - name: Include node-exporter role
  #     ansible.builtin.import_role:
  #       name: dc_node_exporter
  #     vars:
  #       dc_nodeexporter_create_with_userns: "{{ dc_grafana_nodeexporter_create_with_userns }}"
  #       dc_nodeexporter_image_version: "{{ dc_grafana_nodeexporter_image_version }}"
  #       dc_nodeexporter_net_ip: "{{ dc_grafana_net_nodeexporter_ip }}"


  # * ------------------------ Grafana Cadvisor ------------------------ * #
    - name: Include cadvisor role
      ansible.builtin.import_role:
        name: dc_cadvisor
      vars:
        dc_cadvisor_create_with_userns: "{{ dc_grafana_cadvisor_create_with_userns }}"
        dc_cadvisor_image_version: "{{ dc_grafana_cadvisor_image_version }}"
        dc_cadvisor_net_ip: "{{ dc_grafana_net_cadvisor_ip }}"


  # * ------------------------ Grafana Prometheus ------------------------ * #
    - name: Include prometheus role
      ansible.builtin.import_role:
        name: dc_prometheus
      vars:
        dc_prometheus_create_with_userns: "{{ dc_grafana_prometheus_create_with_userns }}"
        dc_prometheus_image_version: "{{ dc_grafana_prometheus_image_version }}"
        dc_prometheus_net_ip: "{{ dc_grafana_net_prometheus_ip }}"


  # * ------------------------ Grafana Vector ------------------------ * #
    - name: Include vector role
      ansible.builtin.import_role:
        name: dc_vector
      vars:
        dc_vector_create_with_userns: "{{ dc_grafana_vector_create_with_userns }}"
        dc_vector_image_version: "{{ dc_grafana_vector_image_version }}"
        dc_vector_net_ip: "{{ dc_grafana_net_vector_ip }}"

  # # * ------------------------ Grafana Alloy ------------------------ * #
  #   - name: Include alloy role
  #     ansible.builtin.import_role:
  #       name: dc_alloy
  #     vars:
  #       dc_alloy_create_with_userns: "{{ dc_grafana_alloy_create_with_userns }}"
  #       dc_alloy_image_version: "{{ dc_grafana_alloy_image_version }}"
  #       dc_alloy_net_ip: "{{ dc_grafana_net_alloy_ip }}"


  # # * ------------------------ Grafana InfluxDB ------------------------ * #
  #   - name: Include InfluxDB role
  #     ansible.builtin.import_role:
  #       name: dc_influxdb_bitnami
  #     vars:
  #       dc_influxdb_bitnami_create_with_userns: "{{ dc_grafana_influxdb_create_with_userns }}"
  #       dc_influxdb_bitnami_image_version: "{{ dc_grafana_influxdb_image_version }}"
  #       dc_influxdb_bitnami_admin_pw: "{{ dc_grafana_influxdb_admin_pw }}"
  #       dc_influxdb_bitnami_user_bucket_name: "{{ dc_grafana_influxdb_user_bucket_name }}"
  #       dc_influxdb_bitnami_user_name: "{{ dc_grafana_influxdb_user_name }}"
  #       dc_influxdb_bitnami_user_pw: "{{ dc_grafana_influxdb_user_pw }}"
  #       dc_influxdb_bitnami_net_ip: "{{ dc_grafana_net_influxdb_ip }}"


  # # * ------------------------ Grafana Elasticsearch ------------------------ * #
  #   - name: Include Elasticsearch role
  #     ansible.builtin.import_role:
  #       name: dc_elasticsearch_bitnami
  #     vars:
  #       dc_elasticsearch_bitnami_create_with_userns: "{{ dc_grafana_elasticsearch_create_with_userns }}"
  #       dc_elasticsearch_bitnami_image_version: "{{ dc_grafana_elasticsearch_image_version }}"
  #       dc_elasticsearch_bitnami_admin_user_name: "{{ dc_grafana_elasticsearch_admin_user_name }}"
  #       dc_elasticsearch_bitnami_admin_user_pw: "{{ dc_grafana_elasticsearch_admin_user_pw }}"
  #       dc_elasticsearch_bitnami_net_ip: "{{ dc_grafana_net_elasticsearch_ip }}"


  # * ----------------------- Grafana App ------------------------- *
    - name: Create app --> {{ app_name }}
      vars:
        container_type: "app" # => app, db, redis
        user: "{{ (dc_grafana_create_with_userns | bool) | ternary(dc_grafana_u_g_id + 100000, dc_grafana_u_g_id) }}"
        group: "{{ (dc_grafana_create_with_userns | bool) | ternary(dc_grafana_u_g_id + 100000, dc_grafana_u_g_id) }}"
      block:
        - name: '[Required] filesystem_manager role'
          ansible.builtin.import_role:
            name: filesystem_manager
          vars:
            filesystem_manager_appdata_directories_to_create:
              - path: "data"
              - path: "data/dashboards"
              - path: "config"
              - path: "config/provisioning/datasources"
              - path: "config/provisioning/dashboards"
            filesystem_manager_appdata_templates_to_copy:
              - src: "grafana.ini.j2"
                dest: "config/grafana.ini"
                mode: '0660'
              - src: "datasources/ds.yml.j2"
                dest: "config/provisioning/datasources/ds.yml"
                mode: '0660'
              - src: "dashboards/dashboards.yml.j2"
                dest: "config/provisioning/dashboards/dashboards.yml"
                mode: '0660'
            filesystem_manager_appdata_files_in_directory_to_copy:
              - src: "{{ playbook_dir | dirname }}/roles/dc_grafana/files/dashboards"
                dest: "data/dashboards"
            filesystem_manager_secret_files_to_create:
              - var_name: dc_grafana_admin_user
                content: "{{ dc_grafana_admin_user }}"
              - var_name: dc_grafana_admin_pw
                content: "{{ dc_grafana_admin_pw }}"

        - name: '[Required] filesystem_manager role for db credentials'
          when: not dc_grafana_use_sqlite
          ansible.builtin.import_role:
            name: filesystem_manager
          vars:
            filesystem_manager_secret_files_to_create:
              - var_name: db_user_pw
                content: "{{ db_user_pw }}"


        - name: Install docker compose grafana with inline definition
          community.docker.docker_compose_v2:
            project_name: "{{ app_name }}"  # eg: grafana
            definition:
              # ! --------------------------- Networks --------------------------- ! #
              networks:
                app_net:
                  name: "{{ app_name }}_net"  # eg: grafana_net
                  external: true  # indicating that it's a pre-existing network not managed by this Docker Compose file.
                traefik_net:
                  name: "{{ dc_traefik_net_name }}"  # eg: traefik_net
                  external: true  # indicating that it's a pre-existing network not managed by this Docker Compose file.

              # * ---------------------------- App ------------------------------ * #
              services:
                grafana:
                  image: grafana/grafana:{{ dc_grafana_image_version }}
                  container_name: "{{ app_name }}"
                  restart: unless-stopped
                  security_opt:
                    - no-new-privileges:true
                  privileged: false
                  userns_mode: "{{ 'host' if dc_grafana_create_with_userns | bool == false else 'remap' }}"
                  user: "{{ dc_grafana_u_g_id }}:{{ dc_grafana_u_g_id }}"
                  networks:
                    app_net: "{{ {'ipv4_address': dc_grafana_net_app_ip} if dc_grafana_net_app_ip is defined and dc_grafana_net_app_ip | length > 0 else {} }}"
                    traefik_net: "{{ {'ipv4_address': dc_traefik_net_grafana_ip} if dc_traefik_net_grafana_ip is defined and dc_traefik_net_grafana_ip | length > 0 else {} }}"
                  # ports:
                  #   - "{{ dc_grafana_port }}:3000"
                  volumes:
                    - "{{ appdata_type_path }}/data:/var/lib/grafana"
                    - "{{ appdata_type_path }}/config/grafana.ini:/etc/grafana/grafana.ini"
                    - "{{ appdata_type_path }}/config/provisioning/datasources/ds.yml:/etc/grafana/provisioning/datasources/ds.yml"
                    - "{{ appdata_type_path }}/config/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
                    - "{{ secrets_type_path }}:/run/secrets"
                  environment:
                    GF_INSTALL_PLUGINS: "grafana-clock-panel"
                    GF_PATHS_CONFIG: "/etc/grafana/grafana.ini"
                    GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
                    GF_SECURITY_ADMIN_USER__FILE: "/run/secrets/dc_grafana_admin_user"
                    GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/dc_grafana_admin_pw"

                    GF_DATABASE_TYPE: "{{ 'postgres' if not dc_grafana_use_sqlite else omit }}"
                    GF_DATABASE_HOST: "{{ dc_grafana_net_db_ip if not dc_grafana_use_sqlite else omit }}"
                    GF_DATABASE_PORT: "{{ db_port if not dc_grafana_use_sqlite else omit }}"
                    GF_DATABASE_NAME: "{{ db_name if not dc_grafana_use_sqlite else omit }}"
                    GF_DATABASE_USER: "{{ db_user_name if not dc_grafana_use_sqlite else omit }}"
                    GF_DATABASE_PASSWORD__FILE: "{{ '/run/secrets/db_user_pw' if not dc_grafana_use_sqlite else omit }}"
                  labels:
                    traefik.enable: "true"
                    ## HTTP Routers
                    traefik.http.routers.grafana-rtr.entrypoints: "websecure"
                    traefik.http.routers.grafana-rtr.rule: "Host(`{{ app_name }}.{{ domain_1 }}`)"
                    ## Middlewares
                    # traefik.http.routers.grafana-rtr.middlewares: "{{ 'chain-authelia@file' if dc_traefik_type == 'ingress' else 'chain-basic-auth@file' }}"
                    traefik.http.routers.grafana-rtr.middlewares: "chain-authelia@file"
                    ## HTTP Services
                    traefik.http.routers.grafana-rtr.service: "grafana-svc"
                    traefik.http.services.grafana-svc.loadbalancer.server.port: "{{ dc_grafana_port }}"


# ! --------------------------- Notes --------------------------- ! #
# ? If the credentials are the same as those of chain-basic-auth, grafana will automatically use them. So do not wonder

# Cleaning
# sudo docker container rm -f grafana-promtail grafana-loki grafana-prometheus grafana-nodeexporter grafana
# sudo docker container rm -f nginx-app
# sudo docker container rm -f grafana-postgresql && sudo docker network rm grafana_net && sudo rm -r $APPDATA_DIR/grafana && sudo rm -r $SECRETS_DIR/grafana

# https://grafana.com/docs/grafana/latest/administration/provisioning/
# https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
# https://www.youtube.com/watch?v=AtxQHiFBn7k

# Promtail and Loki work together for log collection and aggregation, similar to how Node Exporter and Prometheus work together for metrics collection. Here's a breakdown of the equivalence:

#     Promtail ≈ Node Exporter
#         Promtail is to logs what Node Exporter is to metrics.
#         Promtail collects and forwards logs from the host system.
#         Node Exporter collects and exposes system-level metrics.
#     Loki ≈ Prometheus
#         Loki is to logs what Prometheus is to metrics.
#         Loki stores and indexes log data.
#         Prometheus scrapes and stores metric data.

# Key similarities:

#     Data Collection: Both pairs involve a component that collects data from the host system (Promtail for logs, Node Exporter for metrics).
#     Data Storage: Both have a central component that stores the collected data (Loki for logs, Prometheus for metrics).
#     Querying: Both Loki and Prometheus provide query languages for retrieving and analyzing their respective data types.
#     Integration with Grafana: Both Loki and Prometheus integrate well with Grafana for visualization.

# Key differences:

#     Data Type: Promtail/Loki handle log data, while Node Exporter/Prometheus handle metric data.
#     Collection Method: Promtail typically reads log files, while Node Exporter exposes metrics that Prometheus scrapes.
#     Indexing: Loki uses a label-based index for logs, while Prometheus uses a time-series database for metrics.

# In your setup, you would typically have:

#     Promtail on vm1 to collect logs
#     Node Exporter on vm1 to expose metrics
#     Loki on vm2 to receive and store logs from Promtail
#     Prometheus on vm2 to scrape and store metrics from Node Exporter

# ### Grafana Handling of Multiple Datasource Files

# When you create multiple datasource configuration files in Grafana, Grafana will read and merge these configurations during startup or when it reloads its configuration. Here’s how it works:

# #### Multiple Files, Different Datasources
# - If you have multiple files, each defining a different datasource, Grafana will process each file separately and add all defined datasources to its configuration.
#   Each datasource defined in a file is added as a separate entry in Grafana, provided that they have unique `name` fields.

# #### Multiple Files, Same Datasource Name
# - If you have multiple files that define a datasource with the same `name`, Grafana will attempt to merge these configurations. However, the behavior can vary depending on how the settings are specified:
#   - **Identical settings**: If the datasource names and all other settings are identical, Grafana will treat it as a single datasource and there will be no conflicts.
#   - **Different settings**: If the settings (such as `url`, `access`, `basicAuth`, etc.) differ but the `name` is the same, Grafana may merge the configurations, but this can lead to unpredictable behavior.
#     It’s generally recommended to avoid having multiple datasources with the same name but different settings.

# ### Best Practices for Multiple Datasource Files
# 1. **Unique Names**: Ensure that each datasource has a unique `name`. This avoids conflicts and ensures each datasource is properly registered in Grafana.

# 2. **Organize by Function**: If you have different types of datasources (e.g., Prometheus, Loki, InfluxDB), you can organize your files by datasource type. For example, you might have `prometheus.yaml`, `loki.yaml`, and `influxdb.yaml`.

# 3. **Avoid Redundancy**: If possible, avoid defining the same datasource across multiple files with different settings. This can lead to confusion and potential conflicts.

# 4. **Reloading**: Grafana supports reloading datasource configurations without needing to restart the service. This means you can add new datasources by simply placing a new configuration file in the provisioning directory, and Grafana will pick it up.

# Dashboards
# https://voidquark.com/blog/promtail-grafana-dashboard/
