---
- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ pve_vm_image_destination }}"
    state: directory
    mode: '0755'

- name: Check if the ISO already exists
  ansible.builtin.stat:
    path: "{{ pve_vm_image_destination }}/{{ pve_vm_image_url | basename }}"
  register: pve_vm_image_file

- name: Download the ISO if it does not exist
  ansible.builtin.debug:
    msg: "Downloading in progress. This may take a while depending on your internet connection."
  when: not pve_vm_image_file.stat.exists

- name: Download the cloud image if it does not exist
  ansible.builtin.get_url:
    url: "{{ pve_vm_image_url }}"
    dest: "{{ pve_vm_image_destination }}/{{ pve_vm_image_url | basename }}"
    mode: '0644'
  when: not pve_vm_image_file.stat.exists
