---
# handlers file for roles/dc_homepage
- name: Restart homepage
  community.docker.docker_container:
    name: "{{ dc_homepage_container_name }}"
    state: started
    restart: true
  when: dc_homepage_restart_container_on_template_change | default(true)
