---
# handlers file for roles/dc_gluetun
- name: Restart gluetun
  community.docker.docker_container:
    name: "{{ dc_gluetun_container_name }}"
    state: started
    restart: true
  when: dc_gluetun_restart_container_on_template_change | default(true) and gluetun_container_info.exists
