---
# ! Dependencies
# ? Has to be set by vars
# timezone
# domain_1
# dc_traefik_cf_dns_api_token


# * ----------------- Container Configuration -------------------- * #
## * Container variables
dc_traefik_container_name: "traefik"
dc_traefik_create_with_userns: true
dc_traefik_u_g_id: 22003 # with userns --> 122003
dc_traefik_image_version: "3.1"
dc_traefik_log_level: "INFO"

dc_traefik_acme_staging_mode: true  # true = LetsEncrypt Staging Server - false = LetsEncrypt Production Server
dc_traefik_crowdsec_enabled: true
dc_traefik_crowdsec_bouncer_key: "" # Empty for generated key

dc_traefik_basic_auth_user: "AOAUserNotFound"
dc_traefik_basic_auth_password_hashed: "$apr1$z19bu7pc$F4eZc.lSBtThI29L366PS1" # => "404PasswordNotFound" # https://www.web2generators.com/apache-tools/htpasswd-generator
dc_traefik_cloudflare_ip_ranges: >
  173.245.48.0/20, 103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, 141.101.64.0/18,
  108.162.192.0/18, 190.93.240.0/20, 188.114.96.0/20, 197.234.240.0/22, 198.41.128.0/17,
  162.158.0.0/15, 104.16.0.0/13, 104.24.0.0/14, 172.64.0.0/13, 131.0.72.0/22
dc_traefik_local_ip_ranges: ""

# ## * Network settings
# # ? Recommended to add this to the group_vars/all/main.yml or better to the group_vars/all/network.yml
# dc_traefik_net_name: "traefik_net"
# dc_traefik_net_base: 192.168.90
# dc_traefik_net_address: "{{ dc_traefik_net_base }}.0"
# dc_traefik_net_prefix_length: 24
# dc_traefik_net_cidr: "{{ dc_traefik_net_address }}/{{ dc_traefik_net_prefix_length }}"  # 192.168.90.0/24
# dc_traefik_net_ip: "{{ dc_traefik_net_base }}.254"  # 192.168.90.254


# * ------------------- SocketProxy Configuration ---------------------- * #
## * Container variables

## ? Environment variables for socketproxy
dc_traefik_socketproxy_env_log_level: "info"  # debug, info, notice, warning, err, crit, alert and emerg

# * Not always needed - Can expose some information that your service does not need
dc_traefik_socketproxy_env_containers: "1"

# ## * Network settings
# dc_traefik_socketproxy_net_base: 10.100.50
# dc_traefik_socketproxy_net_address: "{{ dc_traefik_socketproxy_net_base }}.0"
# dc_traefik_socketproxy_net_prefix_length: 29 # 6 usable octets eg 10.100.50.2 - 10.100.50.6
# dc_traefik_socketproxy_net_cidr: "{{ dc_traefik_socketproxy_net_address }}/{{ dc_traefik_socketproxy_net_prefix_length }}"  # 10.100.50.0/29
# dc_traefik_socketproxy_net_ip: "{{ dc_traefik_socketproxy_net_base }}.5"  # 10.100.50.5
# dc_traefik_socketproxy_net_app_ip: "{{ dc_traefik_socketproxy_net_base }}.6"  # 10.100.50.6
