# inventories/hosts.yml
all:
  hosts:
# * ---------------------------------------------------------------------------------------- * #
# *                                           PVEs                                           * #
# * ---------------------------------------------------------------------------------------- * #
    pve-aio: &pve_aio_vars
      ansible_host: "{{ default_net_pve_aio_ip }}"
      ansible_user: "{{ pve_root_user_name }}"
# * ---------------------------------------------------------------------------------------- * #
# *                                           VMs                                            * #
# * ---------------------------------------------------------------------------------------- * #
    vm09-aio: &vm09_aio_vars
      ansible_host: "{{ vm09_aio.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm10-ingress: &vm10_ingress_vars
      ansible_host: "{{ vm10_ingress.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm20-metrics: &vm20_metrics_vars
      ansible_host: "{{ vm20_metrics.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm31-application-1: &vm31_application-1_vars
      ansible_host: "{{ vm31_application_1.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm41-multimedia-1: &vm41_multimedia-1_vars
      ansible_host: "{{ vm41_multimedia_1.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm99-testing: &vm99_testing_vars
      ansible_host: "{{ vm99_testing.ip }}"
      ansible_user: "{{ primary_user_name }}"
# * ---------------------------------------------------------------------------------------- * #
# ?                                       Environments                                       * #
# * ---------------------------------------------------------------------------------------- * #
  children:
    prod:
      children:
        pve_servers_env_prod:
          hosts:
            pve-aio_env_prod: *pve_aio_vars  # Yes, naming convention is correct!
        prod_vms:
          hosts:
            prod-vm09-aio: *vm09_aio_vars
            prod-vm10-ingress: *vm10_ingress_vars
            prod-vm20-metrics: *vm20_metrics_vars
            prod-vm31-application-1: *vm31_application-1_vars
            prod-vm41-multimedia-1: *vm41_multimedia-1_vars
            prod-vm99-testing: *vm99_testing_vars
    beta:
    dev:
      children:
        pve_servers_env_dev:
          hosts:
            pve-aio_env_dev: *pve_aio_vars
        dev_vms:
          hosts:
            dev-vm09-aio: *vm09_aio_vars
            dev-vm10-ingress: *vm10_ingress_vars
            dev-vm20-metrics: *vm20_metrics_vars
            dev-vm31-application-1: *vm31_application-1_vars
            dev-vm41-multimedia-1: *vm41_multimedia-1_vars
            dev-vm99-testing: *vm99_testing_vars
    demo:
      children:
        pve_servers_env_demo:
          hosts:
            pve-aio_env_demo: *pve_aio_vars
        demo_vms:
          hosts:
            demo-vm09-aio: *vm09_aio_vars
            demo-vm10-ingress: *vm10_ingress_vars
            demo-vm20-metrics: *vm20_metrics_vars
            demo-vm31-application-1: *vm31_application-1_vars
            demo-vm41-multimedia-1: *vm41_multimedia-1_vars
            demo-vm99-testing: *vm99_testing_vars
