all:
  children:
    pve-servers:
      hosts:
# * ---------------------------------------------------------------------------------------- * #
# *                                           PVEs                                           * #
# * ---------------------------------------------------------------------------------------- * #
        pve01:
          ansible_host: "{{ default_net_pve01_ip }}"
          ansible_user: "{{ pve_root_user_name }}"


# ! Notes:
# The private_key will be set through variables. Therefore, set it there.
# Also as a Hint: id_ecdsa_sk like yubikey requires touch!
