---
# - name: Create VM => demo-vm10-ingress
#   hosts: demo-pve
#   become: true
#   gather_facts: false
#   roles:
#     - role: pve_vm
#       vars:
#         # pve_vm_prune: true  # testing purposes
#         # pve_vm_start_after_create: false
#         pve_vm_id: 110
#         pve_vm_name: "demo-vm10-ingress"
#         pve_vm_hostname: "demo-vm10-ingress"
#         pve_vm_ipv4_address_0: "{{ dc_dmz_net_vm10_ingress_ip }}"


- name: Docker Provisioning
  hosts: demo-vm10-ingress
  become: true
  gather_facts: false
  vars:
    dc_traefik_type: "ingress"
    dc_traefik_crowdsec_enabled: true
  pre_tasks:
    - name: Gather only the hostname fact
      ansible.builtin.setup:
        filter: ansible_hostname
    # ? ensure clock is set / synced otherwise time sensitive things will not work like authelia
    - name: Synchronize system time with NTP
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: restarted
      changed_when: false
  roles:
    - role: app_webmin
    - role: docker_provisioning
    - role: dc_adguard  # ! must be first if used for correct dns
    - role: dc_traefik
    - role: dc_authelia
    - role: dc_authentik
    - role: dc_vector
      vars:
        dc_vector_standalone: true
        dc_vector_create_with_userns: "{{ dc_grafana_vector_create_with_userns }}"
        dc_vector_image_version: "{{ dc_grafana_vector_image_version }}"
        dc_vector_loki_traefik_ip: "{{ dc_dmz_net_vm20_metrics_ip }}" # Has to be the internal ip of the traefik where loki is running
        dc_vector_net_ip: "{{ dc_grafana_net_vector_ip }}" # Will not be used since it is a standalone. Just for reference
        dc_vector_port: "{{ dc_grafana_vector_port }}"
    - role: dc_cadvisor
      vars:
        dc_cadvisor_standalone: true
        dc_cadvisor_create_with_userns: "{{ dc_grafana_cadvisor_create_with_userns }}"
        dc_cadvisor_image_version: "{{ dc_grafana_cadvisor_image_version }}"
        dc_cadvisor_net_ip: "{{ dc_grafana_net_cadvisor_ip }}" # Will not be used since it is a standalone. Just for reference
        dc_cadvisor_port: "{{ dc_grafana_cadvisor_port }}"


# grafana, elasticsearch, influxdb, telegraf should be enough

# Final Decision:
# - Primary Tools: Telegraf or vector (need testing) for both metrics and logs, Elasticsearch and InfluxDB, Grafana for visualization.


# First constelation to test:
# grafana, alertmanager(maybe later), elasticsearch, influxdb, vector (test first) / telegraf
