---
- name: PVE VM
  hosts: pve-qotom
  become: true
  gather_facts: false
  roles:
    - role: pve_vm


# - name: Docker Provisioning
#   hosts: demo-ubuntu-2404-template
#   become: true
#   gather_facts: false
#   vars:
#     domain: "demo.net"
#   tasks:
#     - name: Ping host
#       ansible.builtin.ping:
#       register: ping_result

#     - name: Apply template_to_vm role
#       ansible.builtin.include_role:
#         name: template_to_vm
#       vars:
#         template_to_vm_new_hostname: "demo-VM1-Ingress"
#         template_to_vm_new_ip_address: "{{ dc_demo_net_vm1_ingress_ip }}" # "10.0.100.110"
#         template_to_vm_wait_for_reboot: true
#       when: ping_result is succeeded


# - name: Docker Provisioning
#   hosts: dockthemall-dev1
#   become: true
#   gather_facts: false
#   roles:
#     - role: docker_provisioning
#       vars:
#         docker_provisioning_timezone: "{{ timezone }}"
#         docker_provisioning_primary_user_name: "{{ primary_user_name }}"
#         docker_provisioning_dockerino_user_uid: "{{ dockerino_user_uid }}"
#         docker_provisioning_dockerino_user_gid: "{{ dockerino_user_gid }}"
