---
# - name: Create VM => demo-vm10-ingress
#   hosts: demo-pve
#   become: true
#   gather_facts: false
#   roles:
#     - role: pve_vm
#       vars:
#         # pve_vm_prune: true  # testing purposes
#         # pve_vm_start_after_create: false
#         pve_vm_id: 110
#         pve_vm_name: "demo-vm10-ingress"
#         pve_vm_hostname: "demo-vm10-ingress"
#         pve_vm_ipv4_address_0: "{{ dc_dmz_net_vm10_ingress_ip }}"


- name: Docker Provisioning
  hosts: demo-vm10-ingress
  become: true
  gather_facts: false
  roles:
    - role: docker_provisioning
    - role: dc_traefik
    - role: dc_authelia
    - role: dc_adguard
    - role: dc_it-tools
    - role: dc_authentik
