---
- name: Create VM => demo-vm1-ingress
  hosts: demo-pve
  become: true
  gather_facts: false
  roles:
    - role: pve_vm
      vars:
        # pve_vm_prune: true  # testing purposes
        pve_vm_id: 110
        pve_vm_name: "demo-vm1-ingress"
        pve_vm_hostname: "demo-vm1-ingress"
        pve_vm_ipv4_address_0: "{{ dc_demo_net_vm1_ingress_ip }}"


# - name: Docker Provisioning
#   hosts: demo-vm1-ingress
#   become: true
#   gather_facts: false
#   roles:
#     - role: docker_provisioning
#       vars:
#         docker_provisioning_timezone: "{{ timezone }}"
#         docker_provisioning_primary_user_name: "{{ primary_user_name }}"
#         docker_provisioning_dockerino_user_uid: "{{ dockerino_user_uid }}"
#         docker_provisioning_dockerino_user_gid: "{{ dockerino_user_gid }}"
