---
- name: Create VM => dev-vm10-ingress
  hosts: pve-qotom_env_dev
  become: true
  gather_facts: false
  roles:
    - role: pve_vm
      vars:
        # pve_vm_prune: true  # testing purposes
        # pve_vm_start_after_create: false
        pve_vm_id: "{{ vms_net_vm10_ingress_pve_id }}"
        pve_vm_name: "{{ vms_net_vm10_ingress_hostname }}"
        pve_vm_hostname: "{{ vms_net_vm10_ingress_hostname }}"
        pve_vm_fqdn: "{{ vms_net_vm10_ingress_hostname }}.{{ vms_net_search_domain }}"
        pve_vm_search_domain: "{{ vms_net_search_domain }}"
        pve_vm_ipv4_address_0: "{{ vms_net_vm10_ingress_ip }}"
        pve_vm_bridge_0_name: "{{ vms_net_bridge_name }}"
        pve_vm_net_prefix_length_0: "{{ vms_net_prefix_length }}"


- name: Docker Provisioning
  hosts: dev-vm10-ingress
  become: true
  gather_facts: false
  vars:
    dc_traefik_type: "ingress"  # "This is very important to use either: ingress, metrics, ..." This will match many variables and rules for like traefik! Otherwise change it everywhere!
    # dc_traefik_crowdsec_enabled: false
    host_identifier: "{{ vms_net_vm10_ingress_host_identifier }}"
  pre_tasks:
    - name: Gather only the hostname fact
      ansible.builtin.setup:
        filter: ansible_hostname
    # ? ensure clock is set / synced otherwise time sensitive things will not work like authelia
    - name: Synchronize system time with NTP
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: restarted
      changed_when: false
  roles:
    - role: app_webmin
    - role: docker_provisioning
#     - role: dc_adguard  # ! must be first if used for correct dns
#     - role: dc_traefik
#     # # - role: dc_authentik  # Works perfectly but is overkill for what I need. (extensively tested)
#     - role: dc_authelia # Decided to use authelia. Its lighter and easier to configure than authentik while offering most what I need. (also extensively tested)
#     - role: dc_vector
#       vars:
#         app_name: "standalone" # noqa: var-naming
#         dc_vector_standalone: true
#         dc_vector_create_with_userns: "{{ dc_grafana_vector_create_with_userns }}"
#         dc_vector_image_version: "{{ dc_grafana_vector_image_version }}"
#     - role: dc_cadvisor
#       vars:
#         app_name: "standalone" # noqa: var-naming
#         dc_cadvisor_standalone: true
#         dc_cadvisor_create_with_userns: "{{ dc_grafana_cadvisor_create_with_userns }}"
#         dc_cadvisor_image_version: "{{ dc_grafana_cadvisor_image_version }}"
#     # - role: dc_whoami
#     # - role: dc_portainer
#     # - role: dc_nginx
