---
- name: Create VM => dev-vm20-metrics
  hosts: pve-qotom_env_dev
  become: true
  gather_facts: false
  roles:
    - role: pve_vm
      vars:
        # pve_vm_prune: true  # testing purposes
        # pve_vm_start_after_create: false
        pve_vm_id: "{{ vms_net_vm20_metrics_pve_id }}"
        pve_vm_name: "{{ vms_net_vm20_metrics_hostname }}"
        pve_vm_hostname: "{{ vms_net_vm20_metrics_hostname }}"
        pve_vm_fqdn: "{{ vms_net_vm20_metrics_hostname }}.{{ vms_net_search_domain }}"
        pve_vm_search_domain: "{{ vms_net_search_domain }}"
        pve_vm_ipv4_address_0: "{{ vm20_metrics.ip }}"
        pve_vm_bridge_0_name: "{{ vms_net_bridge_name }}"
        pve_vm_net_prefix_length_0: "{{ vms_net_prefix_length }}"


- name: Docker Provisioning
  hosts: dev-vm20-metrics
  become: true
  gather_facts: false
  vars:
    dc_traefik_type: "metrics"
    dc_traefik_crowdsec_enabled: false
    host_identifier: "{{ vms_net_vm20_metrics_host_identifier }}"
  pre_tasks:
    - name: Gather only the hostname fact
      ansible.builtin.setup:
        filter: ansible_hostname
    # ? ensure clock is set / synced otherwise time sensitive things will not work like authelia
    - name: Synchronize system time with NTP
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: restarted
      changed_when: false
  roles:
    - role: app_webmin
    - role: docker_provisioning
    # - role: dc_traefik
    # - role: dc_grafana
    # - role: dc_whoami
